Improve dashboard
tosuapp/tosu pull request #192
Opened 2024-09-25 10:18 UTC by cyperdark

2024-09-26 22:05 UTC, KotRikD commented
^ удалил чтоб тикет не закрыло

2024-09-26 22:06 UTC, KotRikD commented on packages/server/assets/homepage.js
> +  if (update == true) text = `PP Counter updated: ${name} by ${author}`;
`==` ? Ноги не оторвем от такого?

2024-09-26 22:06 UTC, KotRikD commented on packages/server/assets/homepage.js
> +        .replace(/{options_SELECTED}/gm, option.type == 'options' ? `selected="selected"` : '')
Только заметил, везде `==`, такой же вопрос, что и выше, ноги не отрываем?

2024-09-26 22:08 UTC, KotRikD commented on packages/server/utils/counters.ts
> +                    item._updatable === true
Давай выносить ниже в отдельный хелпер
```js
function checkItemStatus(isUpdatable, isDownloaded) {
// твой код
}
```

2024-09-26 22:09 UTC, KotRikD commented on packages/server/utils/counters.ts
> +                    item._updatable === true
TLDR; https://eslint.org/docs/latest/rules/multiline-ternary

2024-09-26 23:37 UTC, cyperdark commented on packages/server/assets/homepage.js
> +  if (update == true) text = `PP Counter updated: ${name} by ${author}`;
неа, в `update` пока что только undefined или true

2024-09-26 23:37 UTC, cyperdark commented on packages/server/assets/homepage.js
> +        .replace(/{options_SELECTED}/gm, option.type == 'options' ? `selected="selected"` : '')
old code

2024-09-26 23:39 UTC, cyperdark commented on packages/server/utils/counters.ts
> +                    item._updatable === true
нечу функцию сюда, лучше уж такое
![image](https://github.com/user-attachments/assets/7b1c8e10-0057-480b-8bda-a533e60ef745)

2024-10-09 23:16 UTC, KotRikD requested changes

2024-10-09 23:16 UTC, KotRikD commented on packages/server/assets/homepage.js
> +      if (setting.type == 'options')
`==`

2024-10-09 23:16 UTC, KotRikD commented on packages/server/assets/homepage.js
> +      else if (setting.type == 'commands') {
`==`

2024-10-09 23:16 UTC, KotRikD commented on packages/server/assets/homepage.js
> +          if (option.type == 'options' && option.values[option.values.length - 1] != '')
`==`

2024-10-09 23:16 UTC, KotRikD commented on packages/server/assets/homepage.js
> +          if (setting.type == 'options')
`==`

2024-10-09 23:16 UTC, KotRikD commented on packages/server/assets/homepage.js
> +          if (setting.type == 'commands') {
`==`

2024-10-09 23:16 UTC, KotRikD commented on packages/server/assets/homepage.js
> +        if (json.error != null) {
`!=`

2024-10-09 23:16 UTC, KotRikD commented on packages/server/assets/homepage.js
> +          if (typeof json.error == 'object') {
`==`

2024-10-09 23:16 UTC, KotRikD commented on packages/server/assets/homepage.js
> +      const required = items.filter(r => r.required == true && r.name !== '' && r.type != 'checkbox');
`!=`

2024-10-09 23:16 UTC, KotRikD commented on packages/server/assets/homepage.js
> +      if (items.length == 0) {
`==`

2024-10-09 23:16 UTC, KotRikD commented on packages/server/assets/homepage.js
> +      const find = item.options.slice(0, ind).find(r => r.toLowerCase() == value.toLowerCase());
`==` и так далее, лень каждое подсвечивать

2024-10-09 23:16 UTC, KotRikD commented on packages/server/assets/homepage.js
> +      const find = item.options.slice(0, ind).find(r => r.toLowerCase() == value.toLowerCase());
Блин, в добавок мне не нравится как ты называешь find, может лучше result?

2024-10-09 23:16 UTC, KotRikD commented on packages/server/assets/homepage.js
> +  template: `<div class="m-content"><h2 class="ms-title"><span>Settings Builder</span><span>«{{folderName}}»</span></h2><div class="m-scroll settings-container"><div v-for="(i, index) in settings" cl
Это пиздец

2024-10-09 23:16 UTC, KotRikD commented on packages/server/assets/homepage.js
> +      try {
бля у меня ощущение, будто я этот кусок кода уже в сотый раз вижу, если да - может вынести за скоуп?

2024-10-10 00:05 UTC, cyperdark commented on packages/server/assets/homepage.js
> +  template: `<div class="m-content"><h2 class="ms-title"><span>Settings Builder</span><span>«{{folderName}}»</span></h2><div class="m-scroll settings-container"><div v-for="(i, index) in settings" cl
а что с этим поделать, его все равно не возможно редактировать внутри стринга. Так что нет смысла хранить его тут не минифайнутым

2024-10-10 00:13 UTC, cyperdark commented on packages/server/assets/homepage.js
> +      try {
пока что не требуется, плюс я уже нахватался от такого апроача, где такой код был выведен в отдельную функцию, в итоге так функцию улетела за 20+ строк, когда изначально была только на 3-4

так что я не хочу такие мелочи выносить в отдельную функцию, по крайней мере сейчас

2024-10-10 00:18 UTC, cyperdark commented on packages/server/assets/homepage.js
> +      const find = item.options.slice(0, ind).find(r => r.toLowerCase() == value.toLowerCase());
result не подходит, потому что ты там ищешь есть ли повторки, например тут ты добавляешь команду, и ты проверяешь есть ли уже эта команда, так что find тут подходит больше чем result 
![image](https://github.com/user-attachments/assets/7d6e8b24-9fbb-4405-bd4a-140f16eb91d1)

2024-10-10 20:08 UTC, KotRikD commented on packages/server/assets/homepage.js
> +    for (let i = 0; i < props.settings.length; i++) {
Понял) принял)

2024-10-10 20:09 UTC, KotRikD commented on packages/server/assets/homepage.js
> +      try {
хорошо

2024-10-11 09:14 UTC, merged