`Refactor` code with optimizations
tosuapp/tosu pull request #205
Opened 2024-10-13 15:27 UTC by cyperdark

2024-10-14 19:52 UTC, xxCherry commented
Address thing needs to be tested because it might break stuff on 32-bit address space

2024-10-14 23:32 UTC, KotRikD commented on packages/tosu/src/memory/stable.ts
> +    hitErors() {
knock-knock

2024-10-27 12:56 UTC, KotRikD commented on packages/server/router/index.ts
> +                    content += `\n\n\n<script>\rwindow.COUNTERS = ${JSON.stringify(counters)}\r</script>\n`;
Не пофиг на `\n \r` ?

2024-10-27 13:16 UTC, KotRikD requested changes

2024-10-27 13:16 UTC, KotRikD commented on packages/tosu/src/api/utils/buildResultSC.ts
> +enum GradeEnum {
Вынести вне файла в типы, возможно переиспользовать, там где может пригодится (gosu/tosu api)

2024-10-27 13:16 UTC, KotRikD commented on packages/tosu/src/api/utils/buildResultSC.ts
> +        global.status === 2
Давайте статусы уже сделаем enum'ом, тоже самое касается тосу/госу апи, енум взять или у меня, или у чери

2024-10-27 13:16 UTC, KotRikD commented on packages/tosu/src/api/utils/buildResultSC.ts
> +    function formatMilliseconds(ms: number) {
Вынести в утилки

2024-10-27 13:16 UTC, KotRikD commented on packages/tosu/src/api/utils/buildResultV2.ts
> +        global.status === 2 || global.status === 7
про статусы

2024-10-27 13:16 UTC, KotRikD commented on packages/tosu/src/instances/index.ts
> +        this.client = bitness === 64 ? 'lazer' : bitness === 32 ? 'stable' : '';
bitness в енум

2024-10-27 13:16 UTC, KotRikD commented on packages/tosu/src/instances/index.ts
> +        this.client = bitness === 64 ? 'lazer' : bitness === 32 ? 'stable' : '';
Bitness.X86
Bitness.X64

2024-10-27 13:16 UTC, KotRikD commented on packages/tosu/src/instances/lazerInstance.ts
> +        super(pid, 64);
bitness

2024-10-27 13:16 UTC, KotRikD commented on packages/tosu/src/instances/lazerInstance.ts
> +                if (global.status === 7) {
про статусы

2024-10-27 13:16 UTC, KotRikD commented on packages/tosu/src/memory/index.ts
> +export type ScanPatterns = {
Вынести тип в index.types.ts какой-нибудь

2024-10-27 13:16 UTC, KotRikD commented on packages/tosu/src/memory/lazer.ts
> +export enum ScoringMode {
Вынести в отдельный файл

2024-10-27 13:16 UTC, KotRikD commented on packages/tosu/src/memory/lazer.ts
> +export enum OsuSetting {
Вынести в отдельный файл

2024-10-27 13:16 UTC, KotRikD commented on packages/tosu/src/memory/lazer.ts
> +enum HitResult {
Вынести в отдельный файл

2024-10-27 13:16 UTC, KotRikD commented on packages/tosu/src/memory/lazer.ts
> +enum RulesetName {
Вынести в отдельный файл

2024-10-27 13:16 UTC, KotRikD commented on packages/tosu/src/memory/lazer.ts
> +interface Statistics {
Вынести в отдельный файл

2024-10-27 13:16 UTC, KotRikD commented on packages/tosu/src/memory/lazer.ts
> +        const size = this.process.readInt(array + 0x8);
Проверить, что на линуксе нет сдвига по памяти (0x8), в стейбле для этого было `leader.getLeaderStart()` или чот такого рода

2024-10-27 13:16 UTC, KotRikD commented on packages/tosu/src/memory/lazer.ts
> +            const current = this.process.readIntPtr(array + 0x10 + 0x8 * i);
0x8

2024-10-27 13:16 UTC, KotRikD commented on packages/tosu/src/memory/lazer.ts
> +            case 0:
Моды в енумы, пожалуйста

2024-10-27 13:16 UTC, KotRikD commented on packages/tosu/src/memory/lazer.ts
> +        if (username === 'osu!topus') username = 'osu!topus!';
kekw, а зачем так нужно?

2024-10-27 13:16 UTC, KotRikD commented on packages/tosu/src/memory/lazer.ts
> +            status = 2;
про статусы

2024-10-27 13:16 UTC, KotRikD commented on packages/tosu/src/states/gameplay.ts
> +export interface KeyOverlay {
Вынести в отдельный файл

2024-10-27 13:16 UTC, KotRikD commented on packages/tosu/src/states/menu.ts
> +    tested = false;
не используется

2024-10-27 13:16 UTC, KotRikD commented on packages/tosu/src/utils/converters.ts
> +export const numberFromDecimal = (
chore: я в ахуе

2024-10-27 13:16 UTC, KotRikD commented on packages/tosu/src/utils/osuMods.ts
> +export const ModsToName = (modsNumber: number, order?: boolean): string => {
Чо за шарповый нейминг

2024-10-27 13:16 UTC, KotRikD commented on packages/tosu/src/utils/osuMods.ts
> +                modsID += 1;
вот даже не знаю, можно ли тут сделать условно `+= Mods.NF` какой-нибудь или неть

2024-10-27 13:16 UTC, KotRikD commented on packages/tosu/src/utils/osuMods.types.ts
> +    0: {
gamemode.STD
gamoemode.MANIA

etc

2024-10-27 13:16 UTC, KotRikD commented on packages/tsprocess/lib/functions.cc
> +  auto bitness = args[1].As<Napi::Number>().Int32Value();
Куча повторения прям вот этого куска с 19-27 строку, вынесем в отдельную функцию?

2024-10-27 13:16 UTC, KotRikD commented on packages/tsprocess/src/process.ts
> +    constructor(id: number, bitness: number = 32) {
bitness enum

2024-10-28 13:14 UTC, KotRikD commented on packages/tosu/src/api/types/v1.ts
> +    client: 'lazer' | 'stable' | '';
Имею ввиду, что лучше тогда переименовать в | 'unknown'

2024-10-28 22:40 UTC, cyperdark commented on packages/tosu/src/api/types/v1.ts
> +    client: 'lazer' | 'stable' | '';
убрал '' вообще

2024-10-30 10:50 UTC, KotRikD requested changes
Не все обсуждения закрыты

2024-10-31 15:33 UTC, KotRikD commented
# Preliminary approved, waiting for peppy's reply, for confirmation inside the game overlay

2024-11-10 21:46 UTC, KotRikD approved these changes

2024-11-10 21:47 UTC, KotRikD commented
Перед мёржем, все консоль логи на смерть

2024-11-10 21:47 UTC, KotRikD requested changes
Консоль логи почистить

2024-11-11 18:54 UTC, merged

2024-11-11 18:55 UTC, xxCherry commented
🚀